name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          latexmk_use_lualatex: true
      - uses: actions/upload-artifact@v2
        with:
         name: PDF
         path: main.pdf
      - name: Upload file to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: main.pdf
          asset_name: Slides.pdf
          tag: ${{ github.ref }}
          overwrite: true
          body: "Latest Builded Slides"